/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.9 2005/01/07 09:37:18 dts12 Exp $
 */
#ifndef OMCACTIVEINFO_H
#define OMCACTIVEINFO_H

/* function declarations */

/* hc modified for cmcc test 2009-7-16 */
#define CPU_MEM_SAMPLE_TIME 500
typedef struct
{
    unsigned long ulMemTotal;           /* 总的内存容量 */
    unsigned long ulMemUsed;            /* 当前内存使用率 */
    unsigned char ucCpuRate;            /* 当前cpu  使用率 */
    unsigned char ucMaxCpuRate;         /* 最大cpu  使用率 */
    double        dAvgCpuRate;          /* 平均cpu  使用率 */
    double        dMaxMemRate;          /* 最大内存使用率 */
    double        dAvgMemRate;          /* 平均内存使用率 */
    unsigned char aucCpuSampleRate[CPU_MEM_SAMPLE_TIME];  /* cpu  采样缓冲区 */
    double        adMemSampleRate[CPU_MEM_SAMPLE_TIME];   /* 内存采样缓冲区 */
}OMC_CPU_MEM_RATE_T;

extern OMC_CPU_MEM_RATE_T g_CpuMemRate; 
#endif /* OMCACTIVEINFO_H */
