# Hostapd Makefile

HOSTAPD_NAME = hostapd
POWERAC_DIR = ../../powerac
INCLUDE_PATH = -I$(AC_SYSLOG_INCLUDE) \
			   -I./include \
			   -I./include/common \
			   -I./include/net80211 \
			   -I./include/sys \

SOURCES_PATH = ./source: \

CC = gcc

