/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gbcom_core_libsyslog_LibSysLog */

#ifndef _Included_com_gbcom_core_libsyslog_LibSysLog
#define _Included_com_gbcom_core_libsyslog_LibSysLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gbcom_core_libsyslog_LibSysLog
 * Method:    sysLoge
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gbcom_core_libsyslog_LibSysLog_sysLoge
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     com_gbcom_core_libsyslog_LibSysLog
 * Method:    openLog
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_gbcom_core_libsyslog_LibSysLog_openLog
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_gbcom_core_libsyslog_LibSysLog
 * Method:    closeLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gbcom_core_libsyslog_LibSysLog_closeLog
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
