/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gbcom_licencemaker_server_service_EncryptLicenceService */

#ifndef _Included_com_gbcom_licencemaker_server_service_EncryptLicenceService
#define _Included_com_gbcom_licencemaker_server_service_EncryptLicenceService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gbcom_licencemaker_server_service_EncryptLicenceService
 * Method:    getEncryptLicenceFile
 * Signature: ([B[B[B)B
 */
JNIEXPORT jbyte JNICALL Java_com_gbcom_licencemaker_server_service_EncryptLicenceService_getEncryptLicenceFile
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_gbcom_licencemaker_server_service_EncryptLicenceService
 * Method:    encrypt
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_gbcom_licencemaker_server_service_EncryptLicenceService_encrypt
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_gbcom_licencemaker_server_service_EncryptLicenceService
 * Method:    dencrypt
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_gbcom_licencemaker_server_service_EncryptLicenceService_dencrypt
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
