/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.9 2005/01/07 09:37:18 dts12 Exp $
 */
#ifndef TIME_HANDLE_H
#define TIME_HANDLE_H

/* function declarations */
//int init_timerHandle(void);
//Netsnmp_Node_Handler handle_timerHandle;

void oma_check_config_inforce(void);
void oma_check_alarm_report(void);
int do_keyResetConfig(void);
int agent_run_state_set(void);
void oma_save_tlv_data(void);
int check_ip_cfg_flag(void);
/* hc add for dhcp realloc 2009-6-11 */
int check_ac_id_recheck(void);
int check_ac_sample_recheck(void);
int check_cpu_sample(void);
int check_mem_sample(void);

int read_dhcpopt43(void);
int check_auto_up_ver(void);

#endif /* TIME_HANDLE_H */
